package EX_JDBC.Utils;

import EX_JDBC.EXAM0923.Book;


import java.math.BigDecimal;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author SiYi
 * @version 1.0
 * @date 2023/9/22 16:17
 * @desciption:
 */
public class Util_jdbc<T> implements AutoCloseable{
    //工具类的创建
    private String url;
    private String user;
    private String pass;
    private Connection con;
    private PreparedStatement ps;
    private ResultSet rt;
    //考试用
    private DatabaseMetaData md;

    static {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }
    }

    public Util_jdbc(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }

    public Connection getConnection() throws SQLException {
        if (con == null) {
            try {
                con = DriverManager.getConnection(url, user, pass);
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        return con;
    }

    public void close() {
        if (rt != null) {
            try {
                rt.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        if (ps != null) {
            try {
                ps.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
        }
        if (con != null) {
            try {
                con.close();
            } catch (SQLException e) {
                throw new RuntimeException(e);
            }
            con = null;
        }
    }


    //JDBC增删改查

    private void execute(String sql, int autoGeneratedKeys, Object... params) throws SQLException {
        //首先确保con不为null,获取连接
        getConnection();
        ps = con.prepareStatement(sql, autoGeneratedKeys);
        setParams(params);
    }
    public void execute(String sql) throws SQLException {
        //首先确保con不为null,获取连接
        getConnection();
        ps = con.prepareStatement(sql);
        ps.execute();
    }
    public ResultSet executeRt(String sql) throws SQLException {
        //首先确保con不为null,获取连接
        getConnection();
        ps = con.prepareStatement(sql);
        return  ps.executeQuery();

    }
    //---------------

    private int update(String sql, int autoGeneratedKeys, Object... params) throws SQLException {
        //首先确保con不为null,获取连接
      execute(sql,autoGeneratedKeys,params);
        return ps.executeUpdate();
    }
    public int update(String sql, Object... params) throws SQLException {
        //首先确保con不为null,获取连接
       return update(sql,Statement.NO_GENERATED_KEYS,params);
    }

    public int insert(String sql, Object... params) throws SQLException {
        update(sql, Statement.RETURN_GENERATED_KEYS, params);

        //获取结果集
        rt = ps.getGeneratedKeys();
        return rt.next() ? rt.getInt(1) : -1;
    }

    public int delete(String sql, Object... params) throws SQLException {
        return update(sql, Statement.NO_GENERATED_KEYS, params);

    }

    public T selectOne(String sql,IResultMapper<T>resultMapper, Object... params) throws SQLException {
        execute(sql, Statement.NO_GENERATED_KEYS, params);
        rt = ps.executeQuery();

        if (rt.next()) {
            return resultMapper.mapper(rt);
        }return null;
    }

    public List<T> selectList(String sql, IResultMapper<T>resultMapper,Object... params) throws SQLException {
        execute(sql,Statement.NO_GENERATED_KEYS,params);
        rt = ps.executeQuery();
        List list = new ArrayList<>();
        while (rt.next()){
            T t = resultMapper.mapper(rt);
            list.add(t);
        }
        return list;
    }
    public List<T> selectAll(String sql, IResultMapper<T>resultMapper) throws SQLException {
        execute(sql,Statement.NO_GENERATED_KEYS);
        rt = ps.executeQuery();
        List list = new ArrayList<>();
        while (rt.next()){
            T t = resultMapper.mapper(rt);
            list.add(t);
        }
        return list;
    }

    private void setParams(Object... params) throws SQLException {
        if (params != null) {
            for (int i = 0; i < params.length; i++) {
                ps.setObject(i + 1, params[i]);
            }
        }
    }
}



class EmpResultMapper implements IResultMapper<Emp> {

    @Override
    public Emp mapper(ResultSet set) {
        Emp emp = new Emp();
        try {
            emp.setEmpno(set.getInt("empno"));
            emp.setEname(set.getString("ename"));
            emp.setJob(set.getString("job"));
            emp.setHiredate(set.getDate("hiredate"));
            emp.setMgr(set.getInt("mgr"));
            emp.setSal(set.getDouble("SALARY"));
            emp.setComm(set.getDouble("comm"));
            emp.setDeptno(set.getInt("deptno"));
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
        return emp;
    }
}

